apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: kustomwebapp

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-

nameSuffix:
  -v1
